name: Update News Automatically

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # كل يوم 12 بالليل

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (fixed)
        run: |
          sudo apt update
          sudo apt install protobuf-compiler -y
          pip install --upgrade pip
          pip install protobuf
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install feedparser transformers

      - name: Run the news fetch script
        run: |
          python main_real.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add articles/*.html articles/index.json || echo "No articles to add"
          git commit -m "Update articles" || echo "No changes to commit"
          git push
